accounts/urls.py
from django.urls import path
from . import views


urlpatterns = [ 
    path('register/', views.register, name='register'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'), 
    path('new_user_otp_varification/', views.new_user_otp_varification, name='new_user_otp_varification'),
    path('dashboard/',views.dashboard, name='dashboard'),
    path('my_orders/',views.my_orders, name='my_orders'),
    path('edit_profile/',views.edit_profile, name='edit_profile'),
    path('change_password/',views.change_password, name='change_password'),
    path('my_address/',views.my_address, name='my_address'),
    path('add_address/',views.add_address, name='add_address'),

    
    

    # path('activate/<uidb64>/<token>/', views.activate, name='activate'),
]

carts/urls.py
from django.urls import path
from . import views

urlpatterns = [ 
    path('', views.cart, name='cart'),
    path('add_cart_id/<int:product_id>/',views.add_cart_id,name='add_cart_id'),
    path('add_cart/',views.add_cart,name='add_cart'),
    path('remove_cart/',views.remove_cart,name='remove_cart'),
    path('remove_cart_item/',views.remove_cart_item,name='remove_cart_item'),
    path('checkout/',views.checkout,name='checkout'),
]

greatkart/urls.py
from django.contrib import admin
from django.urls import path,include
from.import views
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.home,name='home'),
    path('new-admin/',include("new-admin.urls")),
    path('accounts/', include('accounts.urls')),
    path('category/',include('category.urls')),
    path('store/',include('store.urls')),
    path('cart/',include('carts.urls')),
    path('orders/',include('orders.urls')),
    path('coupon/',include('coupon.urls')),
    path('paypal/', include('paypal.standard.ipn.urls')),
    
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

accounts/models.py
from re import T
from tokenize import blank_re
from typing_extensions import Required
from unittest.util import _MAX_LENGTH
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager

# Create your models here.
class MyAccountManager(BaseUserManager):
    def create_user(self, first_name, last_name, phone_number, username, email, password=None):
        if not email:
            raise ValueError('User must have an email address')

        if not username:
            raise ValueError('User must have an username')

        user = self.model(
            email = self.normalize_email(email),
            username = username,
            first_name = first_name,
            last_name = last_name,
            phone_number = phone_number,
        )


        user.set_password(password)
        user.save(using=self.db)
        return user

    def create_superuser(self, first_name, last_name, phone_number, email, username, password):
        user = self.create_user(
            email = self.normalize_email(email),
            username = username,
            password = password,
            first_name = first_name,
            last_name = last_name,
            phone_number = phone_number,
        )

        user.is_admin = True
        user.is_active = True
        user.is_staff = True
        user.is_superadmin = True
        user.save(using=self.db)
        return user

class Account(AbstractBaseUser):
    first_name      = models.CharField(max_length=50)
    last_name       = models.CharField(max_length=50)
    username        = models.CharField(max_length=50, unique=True )
    email           = models.EmailField(max_length=100, unique=True )
    phone_number    = models.CharField(max_length=50)

    #required
    date_joined     = models.DateField(auto_now_add=True)
    last_login      = models.DateField(auto_now_add=True)
    is_admin        = models.BooleanField(default=False)
    is_staff        = models.BooleanField(default=False)
    is_active       = models.BooleanField(default=False)
    is_superadmin   = models.BooleanField(default=False)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username', 'first_name', 'last_name', 'phone_number']

    objects = MyAccountManager()

    def __str__(self):
        return self.email

    def has_perm(self, perm, obj=None):
        return self.is_admin

    def has_module_perms(self, add_label):
        return True
    

class UserProfile(models.Model):
    user = models.ForeignKey(Account, on_delete=models.CASCADE, )
    address_line_1 = models.CharField(blank=True, max_length=100)
    address_line_2 = models.CharField(blank=True, max_length=100)
    # profile_picture = models.ImageField(blank = True, upload_to = 'userprofile')
    city = models.CharField(blank=True, max_length=20)
    state =  models.CharField(blank=True, max_length=20)
    country = models.CharField(blank=True, max_length=20)


    def __str__(self):
        return self.user.first_name

    def full_address(self):
        return f'{self.address_line_1} {self.address_line_2}'




    



    

orders/models.py
from django.db import models
from accounts.models import Account
from coupon.models import Coupon
from store.models import Product

from django.core.validators import MaxValueValidator, MinValueValidator
from django.db.models.deletion import SET_NULL

# Create your models here.
class Payment(models.Model):
    user = models.ForeignKey(Account, on_delete=models.CASCADE)
    payment_id = models.CharField(max_length=100)
    payment_method = models.CharField(max_length=100)
    amount_paid = models.CharField(max_length=100)
    status = models.CharField(max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)



    def __str__(self):
        return self.payment_id
class Address(models.Model):
    user = models.ForeignKey(Account, on_delete=models.CASCADE, )
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    mobile = models.CharField(max_length=12, blank=True, null=True)
    email = models.EmailField(max_length=50, blank=True, null=True)
    address_line_1 = models.CharField(max_length=100,  blank=True, null=True)
    address_line_2 = models.CharField(max_length=100, blank=True, null=True)
    city            = models.CharField(max_length=50)
    district        = models.CharField(max_length=501)
    country            = models.CharField(max_length=50)
    state           = models.CharField(max_length=50)
    country         = models.CharField(max_length=50, blank=True, null=True)
    pincode         = models.CharField(max_length=10,blank=True, null=True) 

    created_at      = models.DateTimeField(auto_now_add=True)
    updated_at      = models.DateTimeField(auto_now=True)

    def  full_name(self):
        return f'{self.first_name} {self.last_name}'
        
    def full_address(self):
        return f'{self.address_line_1} {self.address_line_2}'
class Order(models.Model):

    STATUS = (
        ('New','New'),
        ('Accepted','Accepted'),
        ('Order Shipped','Order Shipped'),
        ('Order Out for Delivery','Order Out for Delivery'),
        ('Order Delivered','Order Delivered'),
        ('Return','Return'),
        ('Return collected','Return collected'),
        ('Cancelled','Cancelled'),
        
    )

    user = models.ForeignKey(Account, on_delete=models.SET_NULL, null=True)
    payment = models.ForeignKey(Payment, on_delete=models.SET_NULL, blank=True, null=True)
    order_number = models.CharField(max_length=30)
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    phone = models.CharField(max_length=15)
    email = models.EmailField(max_length=50)
    address_line_1 = models.CharField(max_length=50)
    address_line_2 = models.CharField(max_length=50, blank=True)
    country = models.CharField(max_length=50)
    state = models.CharField(max_length=50)
    city = models.CharField(max_length=50)
    order_total = models.FloatField()
    tax = models.FloatField()
    status = models.CharField(max_length=50, choices=STATUS, default='New')
    ip = models.CharField(blank=True, max_length=20)
    is_ordered = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    coupon = models.ForeignKey(Coupon,null=True,on_delete=SET_NULL, blank=True)
    coupon_use_status= models.BooleanField(default=False)
    discount_amount = models.FloatField(null=True,blank=True)
    nett_paid  = models.FloatField(null=True,blank=True)
    discount   = models.IntegerField(default=0,validators=[MinValueValidator(0),MaxValueValidator(100)])


    def full_name(self):
        return f'{self.first_name} {self.last_name}'

    def full_address(self):
        return f'{self.address_line_1} {self.address_line_2}'

    def __str__(self):
        return self.first_name
    def __unicode__(self):
        return self.order_number

        
class OrderProduct(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    payment = models.ForeignKey(Payment, on_delete=models.SET_NULL, blank=True, null=True)
    user = models.ForeignKey(Account, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.IntegerField()
    product_price = models.FloatField()
    ordered = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.product.product_name

accounts/forms.py
from django import forms
from .models import Account, UserProfile


class RegistrationfForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Enter Password',
        'class': 'form-control',
    }))
    confirm_password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Confirm Password'
    }))
    class Meta:
        model = Account
        fields = ['first_name','last_name','phone_number','email', 'password']
    
    def __init__(self, *args, **kwargs):
        super(RegistrationfForm, self).__init__(*args, **kwargs)
        self.fields['first_name'].widget.attrs['placeholder'] = 'Enter First Name'
        self.fields['last_name'].widget.attrs['placeholder'] = 'Enter Last Name'
        self.fields['phone_number'].widget.attrs['placeholder'] = 'Enter Phone Number'
        self.fields['email'].widget.attrs['placeholder'] = 'Enter Email'
        for field in self.fields:
            self.fields[field].widget.attrs['class'] = 'form-control'

    def clean(self):
        cleaned_data = super(RegistrationfForm, self).clean()
        password = cleaned_data.get('password')
        confirm_password = cleaned_data.get('confirm_password')


        if password != confirm_password:
            raise forms.ValidationError(
                "Password does not match"
            )


class UserForm(forms.ModelForm):
    class Meta:
        model = Account
        fields = ('first_name', 'last_name', 'phone_number')

    def __init__(self, *args, **kwargs):
        super(UserForm, self).__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs['class'] = 'form-control'

class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('address_line_1', 'address_line_2', 'city', 'state', 'country')

    def __init__(self, *args, **kwargs):
        super(UserProfileForm, self).__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs['class'] = 'form-control'

templates/accounts/account_verification_email.html
{% autoescape off %}

JI {{user.first_name}},
Please click on below link to confirm your registration.
http://{{doamin}}{% url 'activate' uidb64=uid token=token %}


If you think it's not you, please ignore this email. 

{% endautoescape %}

templates/accounts/add_address.html
{% extends 'base.html' %}
{% load static %}
{%load crispy_forms_tags %} 
{% block content %}



<section class="section-content padding-y bg">
    <div class="container">
    
    <!-- ============================ COMPONENT 1 ================================= -->
    
    <div class="row">
        
        <aside class="col-lg-12">
    
            <div class="card">
            <div class="card-body">
              
               
            <h4 class="card-title mb-4"  >Add Address</h4>
            <form action="{% url 'add_address' %}" id="addAddressForm" method="POST" >
                {% csrf_token %}
                {{form|crispy}}
                    
                    <button type="submit" class="btn btn-primary mt-3">Add</button>
                    </form>
            </div> <!-- card-body.// -->
            </div> <!-- card.// -->
    
    </aside> <!-- col.// -->

    
    </div> <!-- row.// -->
   
    <!-- ============================ COMPONENT 1 END .// ================================= -->
    
    </div> <!-- container .//  -->
    </section>
  
    <script>

        $('#addAddressForm').validate({
        rules:{
            first_name:{
                required:true,
                minlength:3,
                },
            last_name:{
                required:true,
                minlength:1,
                },
            email:{
                required:true,
                email:true,
            },
            mobile:{
                required:true,
                digits:true,
                minlength:10,
                maxlength:10.
            },
            address_line_1:{
                required:true,
                minlength:5,
            },
            address_line_2:{
                required:true,
                
            },
            city:{
                required:true,        
            },
            district:{
                required:true,        
            },
            state:{
                required:true,        
            },
            country:{
                required:true,        
            },
            pincode:{
                required:true,        
            },
        
        },
        messages:{
            first_name:{
                required:"Enter your First name.",
                minlength:"Minimum 3 characters required.",
                },
            last_name:{
                required:"Enter your Last name",
                minlength:"Minimum 1 characters required.",
                },
            email:{
                required:"Enter your Email ID",
                email:"Please enter a valid Email.",
            },
            mobile:{
                required:"Enter your Mobile Number",
                digits:"Only numbers allowed.",
                minlength:"10 digits needed",
                maxlength:"Maximum 10 digits allowed.",
            },
            address_line_1:{
                required:"Address required.",
                minlength:"Need at least 5 characters.",
            },
            address_line_2:{
                required:"Address required.",
                
            },city:{
                required:"Enter City name",        
            },
            district:{
                required:"Enter District name",        
            },
            state:{
                required:"Enter State name",        
            },
            country:{
                required:"Enter Country name",        
            },
            pincode:{
                required:"Enter Pincode",        
            },
        
        },
        })
        
        $('#id_mobile').keyup(validateMaxLength);
        function validateMaxLength(){
                var text = $(this).val();
                var maxlength = 10;
                if(maxlength > 0)  
                {
                        $(this).val(text.substr(0, maxlength)); 
                }
        }
            </script>
{% endblock %}

templates/accounts/change_password.html
{% extends 'base.html' %}


{% block content %}

<section class="section-conten padding-y bg">

{% include 'includes/alerts.html' %}
<div class="container">
	<div class="row">
{% include 'includes/dashboard_sidebar.html' %}
		<main class="col-md-9">
		<article class="card">
		<header class="card-header">
			<strong class="d-inline-block mr-3">Change your password</strong>

		</header> 
		<div class="card-body">
			
			<div class="row">
			<div class="col-md-12">
				<form action="{% url 'change_password' %}" method="POST" enctype="multipart/form-data">
					{% csrf_token %}
				
				
					<div class="form-group">
						<label>Current Password</label>
						<input type="password" name="current_password" placeholder="Current Password" class="form-control" required>
					</div>
					<div class="form-group">
						<label>Create New Password</label>
						<input type="password" name="new_password" placeholder="Create New Password" class="form-control" required>
					</div>
                    <div class="form-group">
						<label>Confirm New Password</label>
						<input type="password" name="confirm_password" placeholder="Confirm New Password" class="form-control" required>
					</div>
					
					
					<input type="submit" value="update" class="btn btn-primary">
				</form>
			</div>

			</div> <!-- row.// -->
		</div> <!-- card-body .// -->

		</article> <!-- order-group.// -->
	</main>
</div> <!-- row.// -->
</div>


</section>

{% endblock %}

templates/accounts/dashboard.html
{% extends 'base.html' %}


{% block content %}

<section class="section-conten padding-y bg">

{% include 'includes/alerts.html' %}
<div class="container">
	<div class="row">
	{% include 'includes/dashboard_sidebar.html' %}
	<main class="col-md-9">
		<article class="card">
		<header class="card-header">
			<strong class="d-inline-block mr-3">Logged in as:</strong>
			<span>{{user.full_name}}</span>
		</header>
		<div class="card-body">
			<div class="row">

			<div class="col-md-6">
				<div class="card" style="text-align:center;">
					<div class="card-body">
						<h5 class="card-title">Total Orders : {{orders_count}}</h5>
						
						<a href="{% url 'my_orders' %}">View Orders</a>
					</div>
				</div>
			</div>
			<div class="col-md-6">
				<div class="card" style="text-align:center;">
					<div class="card-body">
						<!-- <img src="{{userprofile.profile_picture.url}}" alt="User Profile Picture" width="50" height="50" style="border-radius:50%;"> -->
						<p class="mb-0">{{user.email}}</p>
						<p>{{user.phone_number}}</p>
					</div>
				</div>
			</div>

			</div> <!-- row.// -->
		</div> <!-- card-body .// -->

		</article> <!-- order-group.// -->
	</main>
</div> <!-- row.// -->
</div>


</section>

{% endblock %}

templates/accounts/edit_profile.html
{% extends 'base.html' %}


{% block content %}

<section class="section-conten padding-y bg">

{% include 'includes/alerts.html' %}
<div class="container">
	<div class="row">
{% include 'includes/dashboard_sidebar.html' %}
		<main class="col-md-9">
		<article class="card">
		<header class="card-header">
			<strong class="d-inline-block mr-3">Edit your profile</strong>

		</header> 
		<div class="card-body">
			
			<div class="row">
			<div class="col-md-12">
				<form action="{% url 'edit_profile' %}" id="editProfileForm" method="POST" enctype="multipart/form-data">
					{% csrf_token %}
					<div class="form-row">
						<div class="form-group col-md-6">
							<label>First Name</label>
							{{user_form.first_name}}
						</div>
						<div class="form-group col-md-6">
							<label>Last Name</label>
							{{user_form.last_name}}
						</div>
					</div>
					<div class="form-row">
						<div class="form-group col-md-6">
							<label>Phone Number</label>
							{{user_form.phone_number}}
						</div>
						
					</div>
					<div class="form-group">
						<label>Address Line 1</label>
						{{profile_form.address_line_1}}
					</div>
					<div class="form-group">
						<label>Address Line 2</label>
						{{profile_form.address_line_2}}
					</div>
					<div class="form-row">
						<div class="form-group col-md-4">
							<label>City</label>
							{{profile_form.city}}
						</div>
						<div class="form-group col-md-4">
							<label>State</label>
							{{profile_form.state}}
						</div>
						<div class="form-group col-md-4">
							<label>Country</label>
							{{profile_form.country}} 
						</div>
					</div>
					<input type="submit" value="Save" class="btn btn-primary">
				</form>
			</div>

			</div> <!-- row.// -->
		</div> <!-- card-body .// -->

		</article> <!-- order-group.// -->
	</main>
</div> <!-- row.// -->
</div>


</section>

<script>


	$('#editProfileForm').validate({
	rules:{
		first_name:{
			required:true,
			minlength:3,
			},
		last_name:{
			required:true,
			minlength:1,
			},
		email:{
			required:true,
			email:true,
		},
		phone_number:{
			required:true,
			digits:true,
			minlength:10,
			maxlength:10.
		},
		address_line_1:{
			required:true,
			minlength:5,
		},
		address_line_2:{
			required:true,
			
		},
		city:{
			required:true,        
		},
		district:{
			required:true,        
		},
		state:{
			required:true,        
		},
		country:{
			required:true,        
		},
		pincode:{
			required:true,        
		},
	
	},
	messages:{
		first_name:{
			required:"Enter your First name.",
			minlength:"Minimum 3 characters required.",
			},
		last_name:{
			required:"Enter your Last name",
			minlength:"Minimum 1 characters required.",
			},
		email:{
			required:"Enter your Email ID",
			email:"Please enter a valid Email.",
		},
		phone_number:{
			required:"Enter your Mobile Number",
			digits:"Only numbers allowed.",
			minlength:"10 digits needed",
			maxlength:"Maximum 10 digits allowed.",
		},
		address_line_1:{
			required:"Address required.",
			minlength:"Need at least 5 characters.",
		},
		address_line_2:{
			required:"Address required.",
			
		},city:{
			required:"Enter City name",        
		},
		district:{
			required:"Enter District name",        
		},
		state:{
			required:"Enter State name",        
		},
		country:{
			required:"Enter Country name",        
		},
		pincode:{
			required:"Enter Pincode",        
		},
	
	},
	})
	
	$('#id_phone_number').keyup(validateMaxLength);
	function validateMaxLength(){
			var text = $(this).val();
			var maxlength = 10;
			if(maxlength > 0)  
			{
					$(this).val(text.substr(0, maxlength)); 
			}
	}
	
		</script>

{% endblock %}

templates/accounts/login.html
{% extends 'base.html' %}
{% block content %}

<!-- ========================= SECTION CONTENT ========================= -->
<section class="section-conten padding-y" style="min-height:84vh">

    <!-- ============================ COMPONENT LOGIN   ================================= -->
        <div class="card mx-auto" style="max-width: 380px; margin-top:100px;">
          <div class="card-body">
              
          <h4 class="card-title mb-4">Sign in</h4>
          {% include 'includes/alerts.html' %}
          <form action="{% url 'login' %}" method="POST">
              {% csrf_token %}
              <div class="form-group">
                 <input type="email" class="form-control" placeholder="Email Address" name="email" >
              </div> <!-- form-group// -->
              <div class="form-group">
                <input type="password" class="form-control" placeholder="Password" name="password" >
              </div> <!-- form-group// -->
              
              <div class="form-group">
                  <a href="#" class="float-right">Forgot password?</a> 
               
              </div> <!-- form-group form-check .// -->
              <div class="form-group">
                  <button type="submit" class="btn btn-primary btn-block"> Login  </button>
              </div> <!-- form-group// -->    
          </form>
          </div> <!-- card-body.// -->
        </div> <!-- card .// -->
    
         <p class="text-center mt-4">Don't have account? <a href="{% url 'register' %}">Sign up</a></p>
         <br><br>
    <!-- ============================ COMPONENT LOGIN  END.// ================================= -->
    
    
    </section>
    <!-- ========================= SECTION CONTENT END// ========================= -->
    

{% endblock %}

templates/accounts/my_address.html
{% for address in address  %}
{{address.address_line_1}}
{% endfor %}



<a href="{% url 'add_address' %}" class="btn btn-primary">Add Address</a>

templates/accounts/new_user_otp_page.html
{% extends 'base.html' %}
{% block content %}

<!-- ========================= SECTION CONTENT ========================= -->
<section class="section-conten padding-y" style="min-height:84vh">

    <!-- ============================ COMPONENT LOGIN   ================================= -->
        <div class="card mx-auto" style="max-width: 380px; margin-top:100px;">
          <div class="card-body">
              
          <h4 class="card-title mb-4">Enter Otp</h4>
          {% include 'includes/alerts.html' %}
          <form action="#" method="POST">
              {% csrf_token %}
              <div class="form-group">
                 <input type="text" class="form-control" placeholder="enter otp" name="otp" >
              </div> <!-- form-group// -->
              
              
            
              <div class="form-group">
                  <button type="submit" class="btn btn-primary btn-block"> Login  </button>
              </div> <!-- form-group// -->    
          </form>
          </div> <!-- card-body.// -->
        </div> <!-- card .// -->
    
         <p class="text-center mt-4">Don't have account? <a href="{% url 'register' %}">Sign up</a></p>
         <br><br>
    <!-- ============================ COMPONENT LOGIN  END.// ================================= -->
    
    
    </section>
    <!-- ========================= SECTION CONTENT END// ========================= -->
    

{% endblock %}

templates/accounts/register.html
{% extends 'base.html' %}
{% block content %}
<!-- ========================= SECTION CONTENT ========================= -->
<section class="section-content padding-y">

    <!-- ============================ COMPONENT REGISTER   ================================= -->
        <div class="card mx-auto" style="max-width:520px; margin-top:40px;">
          <article class="card-body">
              {% include 'includes/alerts.html' %}
            <header class="mb-4"><h4 class="card-title">Sign up</h4></header>
            <form action="{% url 'register' %}"  id="registerForm"  method="POST">
                {% csrf_token %}


               
                    <div class="form-row">
                        <div class="col form-group">
                            <label>First name</label>
                              {{form.first_name}}
                        </div> <!-- form-group end.// -->
                        <div class="col form-group">
                            <label>Last name</label>
                            {{form.last_name}}
                        </div> <!-- form-group end.// -->
                    </div> <!-- form-row end.// -->
                   
                   
                    <div class="form-row">
                        <div class="form-group col-md-6">
                          <label>Email</label>
                          {{form.email}}
                        </div> <!-- form-group end.// -->
                        <div class="form-group col-md-6">
                          <label>Phone</label>
                          {{form.phone_number}}
                        </div> <!-- form-group end.// -->
                    </div> <!-- form-row.// -->
                    <div class="form-row">
                        <div class="form-group col-md-6">
                            <label>Create password</label>
                            {{form.password}}
                        </div> <!-- form-group end.// --> 
                        <div class="form-group col-md-6">
                            <label>Repeat password</label>
                            {{form.confirm_password}}
                        </div> <!-- form-group end.// -->  
                    </div>
                    <div class="form-group">
                        <button type="submit" class="btn btn-primary btn-block"> Register  </button>
                    </div> <!-- form-group// -->   
                    {{form.email.errors}}   
                    {{form.non_field_errors}}
                        
                </form>
            </article><!-- card-body.// -->
        </div> <!-- card .// -->
        <p class="text-center mt-4">Have an account? <a href="{% url 'login' %}">Log In</a></p>
        <br><br>
    <!-- ============================ COMPONENT REGISTER  END.// ================================= -->
    
    
    </section>
    <!-- ========================= SECTION CONTENT END// ========================= -->
    
    <script>
        $('#registerForm').validate({
        rules:{
            first_name:{
                required:true,
                minlength:3,
                },
            last_name:{
                required:true,
                minlength:1,
                },
            email:{
                required:true,
                email:true,
            },
            phone_number:{
                required:true,
                digits:true,
                minlength:10,
                maxlength:10.
            },
            password:{
                required:true,
                minlength:5,
            },
        
            confirm_password:{
                required:true,
                
                minlength:5,
                equalTo:"#id_password",
                
            },
        
        },
        messages:{
            first_name:{
                required:"Enter your First name.",
                minlength:"Minimum 3 characters required.",
                },
            last_name:{
                required:"Enter your Last name",
                minlength:"Minimum 1 characters required.",
                },
            email:{
                required:"Enter your Email ID",
                email:"Please enter a valid Email.",
            },
            phone_number:{
                required:"Enter your Mobile Number",
                digits:"Only numbers allowed.",
                minlength:"10 digits needed",
                maxlength:"Maximum 10 digits allowed.",
            },
            password:{
                required:"Password required.",
                minlength:"Need at least 5 characters.",
            },
        
            confirm_password:{
                required:"Re-enter password",
                equalTo:"The passwords must be the same.",
                minlength:"Must be of same length as of the Password",
                
            },
        },
        })
        
        
        $('#id_phone_number').keyup(validateMaxLength);
        function validateMaxLength(){
                var text = $(this).val();
                var maxlength = 10;
                if(maxlength > 0)  
                {
                        $(this).val(text.substr(0, maxlength)); 
                }
        }
          </script>
{% endblock %}